import { Inter } from 'next/font/google'
import './globals.css'
import Authprovider from "./Provider"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next-Auth',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Authprovider>
        <body className={inter.className}>{children}</body>
      </Authprovider>
    </html>
  )
}
